# Generated by Django 3.2.4 on 2021-06-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
