# Generated by Django 3.2.4 on 2021-06-12 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_publication_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
