# Generated by Django 3.2.4 on 2021-06-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0006_auto_20210613_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publication',
            name='follow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publication',
            name='slug',
            field=models.SlugField(max_length=250, null=True, unique=True),
        ),
    ]
