# Generated by Django 3.2.4 on 2021-06-13 16:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publications', '0008_publicationattachment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PublicationAttachment',
            new_name='Attachment',
        ),
    ]
