# Generated by Django 3.2.4 on 2021-06-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0009_rename_publicationattachment_attachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='attachment',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
