# Generated by Django 3.2.4 on 2021-06-13 16:55

from django.db import migrations, models
import publications.models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0010_auto_20210613_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to=publications.models.attachment_directory_path),
        ),
    ]
