# Generated by Django 3.2.4 on 2021-06-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0011_alter_attachment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
