# Generated by Django 3.2.4 on 2021-06-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0012_publication_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={},
        ),
        migrations.AlterField(
            model_name='attachment',
            name='name',
            field=models.CharField(default='relating document', max_length=50),
        ),
    ]
