# Generated by Django 3.2.4 on 2021-06-13 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0014_auto_20210613_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='dept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='publications.department'),
        ),
    ]
